[package]
name = "dialog_relay"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
nostr-relay-builder = "0.42.0"
tokio = { version = "1.45.1", features = ["signal"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
